// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label5;
void ui_event_ImgButtonBread(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonBread;
void ui_event_ImgButtonPay(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonPay;
void ui_event_ImgButtonCupcake(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonCupcake;
void ui_event_ImgButtonCrois(lv_event_t * e);
extern lv_obj_t * ui_ImgButtonCrois;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_TextArea3;
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_Image6;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image4;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Image5;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui____initial_actions0;
int ui_cardDetected;
int ui_resetMCU;


LV_IMG_DECLARE(ui_img_rainbow_banner_png);    // assets\rainbow_banner.png
LV_IMG_DECLARE(ui_img_logoleahscafe_png);    // assets\logoLeahsCafe.png
LV_IMG_DECLARE(ui_img_2049135699);    // assets\mathafix-pain_rel.png
LV_IMG_DECLARE(ui_img_589022287);    // assets\mathafix-pain02.png
LV_IMG_DECLARE(ui_img_payment_png);    // assets\payment.png
LV_IMG_DECLARE(ui_img_payment_clicked_png);    // assets\payment_clicked.png
LV_IMG_DECLARE(ui_img_cupcake_png);    // assets\cupcake.png
LV_IMG_DECLARE(ui_img_cupcake02_png);    // assets\cupcake02.png
LV_IMG_DECLARE(ui_img_croissant_02_png);    // assets\croissant_02.png
LV_IMG_DECLARE(ui_img_croissant_03_png);    // assets\croissant_03.png
LV_IMG_DECLARE(ui_img_cancel_png);    // assets\cancel.png
LV_IMG_DECLARE(ui_img_cancel02_png);    // assets\cancel02.png
LV_IMG_DECLARE(ui_img_1635345530);    // assets\Wifi-Signal-3.png
LV_IMG_DECLARE(ui_img_thankyou_png);    // assets\thankYou.png
LV_IMG_DECLARE(ui_img_checkmark_png);    // assets\checkMark.png
LV_IMG_DECLARE(ui_img_checkmark02_png);    // assets\checkMark02.png
LV_IMG_DECLARE(ui_img_croissant_01_png);    // assets\croissant_01.png
LV_IMG_DECLARE(ui_img_g10_png);    // assets\g10.png
LV_IMG_DECLARE(ui_img_g3612_png);    // assets\g3612.png
LV_IMG_DECLARE(ui_img_g3613_png);    // assets\g3613.png
LV_IMG_DECLARE(ui_img_gauge03_png);    // assets\gauge03.png
LV_IMG_DECLARE(ui_img_rect504_png);    // assets\rect504.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
