// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Screen1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Screen1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Screen1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
// lv_obj_set_style_bg_img_src( ui_Screen1, &TemporaryImage, LV_PART_SCROLLBAR | LV_STATE_PRESSED );

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_rainbow_banner_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 108
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_Image1, -6 );
lv_obj_set_y( ui_Image1, -129 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_logoleahscafe_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 200
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_Image2, -3 );
lv_obj_set_y( ui_Image2, -132 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -13 );
lv_obj_set_y( ui_Label2, -82 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"$2.00");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -13 );
lv_obj_set_y( ui_Label1, 44 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"$4.00");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -13 );
lv_obj_set_y( ui_Label3, -23 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"$3.00");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 75);
lv_obj_set_height( ui_Panel2, 159);
lv_obj_set_x( ui_Panel2, 59 );
lv_obj_set_y( ui_Panel2, -18 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xECE9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Panel2, lv_color_hex(0xA49D9D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Panel2, 75, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Panel2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Panel2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -23 );
lv_obj_set_y( ui_Label8, -60 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"$");

ui_Label7 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -23 );
lv_obj_set_y( ui_Label7, -6 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"$");

ui_Label10 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -23 );
lv_obj_set_y( ui_Label10, 60 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"$");

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -15 );
lv_obj_set_y( ui_Label5, 86 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Total");

ui_ImgButtonBread = lv_imgbtn_create(ui_Screen1);
lv_imgbtn_set_src(ui_ImgButtonBread, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_2049135699, NULL);
lv_imgbtn_set_src(ui_ImgButtonBread, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_589022287, NULL);
lv_obj_set_height( ui_ImgButtonBread, 50);
lv_obj_set_width( ui_ImgButtonBread, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButtonBread, -75 );
lv_obj_set_y( ui_ImgButtonBread, 49 );
lv_obj_set_align( ui_ImgButtonBread, LV_ALIGN_CENTER );

ui_ImgButtonPay = lv_imgbtn_create(ui_Screen1);
lv_imgbtn_set_src(ui_ImgButtonPay, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_payment_png, NULL);
lv_imgbtn_set_src(ui_ImgButtonPay, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_payment_clicked_png, NULL);
lv_obj_set_height( ui_ImgButtonPay, 39);
lv_obj_set_width( ui_ImgButtonPay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButtonPay, -70 );
lv_obj_set_y( ui_ImgButtonPay, 126 );
lv_obj_set_align( ui_ImgButtonPay, LV_ALIGN_CENTER );

ui_ImgButtonCupcake = lv_imgbtn_create(ui_Screen1);
lv_imgbtn_set_src(ui_ImgButtonCupcake, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cupcake_png, NULL);
lv_imgbtn_set_src(ui_ImgButtonCupcake, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cupcake02_png, NULL);
lv_obj_set_height( ui_ImgButtonCupcake, 69);
lv_obj_set_width( ui_ImgButtonCupcake, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButtonCupcake, -75 );
lv_obj_set_y( ui_ImgButtonCupcake, -22 );
lv_obj_set_align( ui_ImgButtonCupcake, LV_ALIGN_CENTER );

ui_ImgButtonCrois = lv_imgbtn_create(ui_Screen1);
lv_imgbtn_set_src(ui_ImgButtonCrois, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_croissant_02_png, NULL);
lv_imgbtn_set_src(ui_ImgButtonCrois, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_croissant_03_png, NULL);
lv_obj_set_height( ui_ImgButtonCrois, 36);
lv_obj_set_width( ui_ImgButtonCrois, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButtonCrois, -75 );
lv_obj_set_y( ui_ImgButtonCrois, -80 );
lv_obj_set_align( ui_ImgButtonCrois, LV_ALIGN_CENTER );

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 36 );
lv_obj_set_y( ui_Label6, 86 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"$");

ui_TextArea2 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea2, 65);
lv_obj_set_height( ui_TextArea2, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_TextArea2, 64 );
lv_obj_set_y( ui_TextArea2, -78 );
lv_obj_set_align( ui_TextArea2, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea2,"0.00");
lv_textarea_set_placeholder_text(ui_TextArea2,"Placeholder...");
lv_textarea_set_one_line(ui_TextArea2,true);
lv_obj_set_style_bg_color(ui_TextArea2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextArea2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextArea2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_TextArea1 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea1, 60);
lv_obj_set_height( ui_TextArea1, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_TextArea1, 64 );
lv_obj_set_y( ui_TextArea1, -24 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea1,"0.00");
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");
lv_textarea_set_one_line(ui_TextArea1,true);
lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextArea1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_TextArea3 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea3, 61);
lv_obj_set_height( ui_TextArea3, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_TextArea3, 64 );
lv_obj_set_y( ui_TextArea3, 42 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea3,"0.00");
lv_textarea_set_placeholder_text(ui_TextArea3,"Placeholder...");
lv_textarea_set_one_line(ui_TextArea3,true);
lv_obj_set_style_bg_color(ui_TextArea3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextArea3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextArea3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_TextArea4 = lv_textarea_create(ui_Screen1);
lv_obj_set_width( ui_TextArea4, 61);
lv_obj_set_height( ui_TextArea4, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_TextArea4, 65 );
lv_obj_set_y( ui_TextArea4, 86 );
lv_obj_set_align( ui_TextArea4, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextArea4,"0.00");
lv_textarea_set_placeholder_text(ui_TextArea4,"Placeholder...");
lv_textarea_set_one_line(ui_TextArea4,true);
lv_obj_set_style_bg_color(ui_TextArea4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextArea4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextArea4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Image6 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image6, &ui_img_cancel_png);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image6, 195 );
lv_obj_set_y( ui_Image6, 283 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImgButton3 = lv_imgbtn_create(ui_Screen1);
lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cancel_png, NULL);
lv_imgbtn_set_src(ui_ImgButton3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_cancel02_png, NULL);
lv_obj_set_height( ui_ImgButton3, 37);
lv_obj_set_width( ui_ImgButton3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_ImgButton3, 65 );
lv_obj_set_y( ui_ImgButton3, 126 );
lv_obj_set_align( ui_ImgButton3, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_ImgButtonBread, ui_event_ImgButtonBread, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButtonPay, ui_event_ImgButtonPay, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButtonCupcake, ui_event_ImgButtonCupcake, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButtonCrois, ui_event_ImgButtonCrois, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ImgButton3, ui_event_ImgButton3, LV_EVENT_ALL, NULL);

}
